#!/usr/bin/env bats

setup() {
  source "${BATS_TEST_DIRNAME}/../../lib/jsonevent.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/preflight.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/chainload.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/secureboot.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/migrate.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/doctor.sh"
  source "${BATS_TEST_DIRNAME}/../../lib/revert.sh"
}

@test "grub_backup_is_complete true only when MANIFEST exists" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  run grub_backup_is_complete "$d"
  [ "$status" -ne 0 ]
  : > "$d/MANIFEST"
  run grub_backup_is_complete "$d"
  [ "$status" -eq 0 ]
}

@test "grub_bootloader_id_from_backup parses the real label, and falls back to Xero-Linux (not GRUB, not XeroLinux) when capture failed" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  printf 'Boot0003* XeroLinux\tHD(1,GPT,x)/File(\\EFI\\XeroLinux\\grubx64.efi)\n' > "$d/nvram-grub.txt"
  [ "$(grub_bootloader_id_from_backup "$d")" = "XeroLinux" ]
  rm -f "$d/nvram-grub.txt"
  # Hyphenated, deliberately: never collides in the firmware boot menu
  # with Limine's own hardcoded "XeroLinux" label, and isn't the generic
  # "GRUB" either.
  [ "$(grub_bootloader_id_from_backup "$d")" = "Xero-Linux" ]
}

@test "backup_grub_state previews under DRY_RUN without writing anything" {
  d="$BATS_TEST_TMPDIR/bk"
  DRY_RUN=1
  run backup_grub_state /boot/efi "$d"
  [ "$status" -eq 0 ]
  [[ "$output" == *"would_run"* ]]
  [ ! -e "$d/MANIFEST" ]
}

@test "snapshot_kernel_state_for_backup records a timestamp and the currently-installed kernel packages" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  pacman() {
    if [[ "$1" == "-Q" ]]; then printf 'linux 6.10.1-1\nvim 9.0-1\n'; fi
  }
  export -f pacman
  snapshot_kernel_state_for_backup "$d"
  [[ "$(cat "$d/timestamp.txt")" =~ ^[0-9]+$ ]]
  [[ "$(cat "$d/kernel-packages.txt")" == "linux 6.10.1-1" ]]
}

@test "backup_grub_state_staleness_warning: nothing to warn about when recent and kernel packages match" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  now=1700000000
  printf '%s' "$now" > "$d/timestamp.txt"
  printf 'linux 6.10.1-1\n' > "$d/kernel-packages.txt"
  run backup_grub_state_staleness_warning "$d" "$now" 30 "linux 6.10.1-1"
  [ "$status" -ne 0 ]
  [ -z "$output" ]
}

@test "backup_grub_state_staleness_warning: warns when the backup is older than the age threshold" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  printf '%s' "1000000000" > "$d/timestamp.txt"
  now=$((1000000000 + 40 * 86400))
  run backup_grub_state_staleness_warning "$d" "$now" 30
  [ "$status" -eq 0 ]
  [[ "$output" == *"40 days old"* ]]
}

@test "backup_grub_state_staleness_warning: warns when kernel packages differ from backup time, even if recent" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  now=1700000000
  printf '%s' "$now" > "$d/timestamp.txt"
  printf 'linux 6.10.1-1\n' > "$d/kernel-packages.txt"
  run backup_grub_state_staleness_warning "$d" "$now" 30 $'linux 6.11.0-1\n'
  [ "$status" -eq 0 ]
  [[ "$output" == *"Kernel packages have changed"* ]]
}

@test "backup_grub_state_staleness_warning: nothing to warn about when there is no recorded timestamp (older backup format)" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d"
  run backup_grub_state_staleness_warning "$d" "1700000000" 30 ""
  [ "$status" -ne 0 ]
  [ -z "$output" ]
}

@test "cmd_revert emits a staleness warning event when the backup is stale, without blocking the revert" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  printf '%s' "1000000000" > "$XSB_BACKUP_DIR/timestamp.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  backup_grub_state_staleness_warning() { printf 'simulated staleness warning'; return 0; }
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *'"level":"warning"'*"simulated staleness warning"* ]]
  [[ "$output" == *"revert_done"* ]]
}

@test "restore_grub_files previews a whole-directory /etc/default restore and grubenv, but NOT grub.cfg (that's regenerated by grub-mkconfig instead)" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d/etc-default" "$d/boot-grub"
  printf 'GRUB_DEFAULT=0\n' > "$d/etc-default/grub"
  printf 'wallpaper: boot():/splash.png\n' > "$d/etc-default/limine"
  printf 'saved_entry=0\n' > "$d/boot-grub/grubenv"
  printf 'this is a stale, backed-up grub.cfg that must never be restored\n' > "$d/boot-grub/grub.cfg"
  DRY_RUN=1
  result="$(restore_grub_files "$d")"
  [[ "$result" == *"would_run"*"rm -rf /etc/default"* ]]
  [[ "$result" == *"would_run"*"cp -a $d/etc-default /etc/default"* ]]
  [[ "$result" == *"would_run"*"boot-grub/grubenv"*"/boot/grub/grubenv"* ]]
  [[ "$result" != *"grub.cfg"* ]]
}

@test "restore_grub_files falls back to restoring just /etc/default/grub when the backup predates the whole-directory format" {
  d="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$d/boot-grub"
  printf 'GRUB_DEFAULT=0\n' > "$d/etc-default-grub"
  printf 'saved_entry=0\n' > "$d/boot-grub/grubenv"
  DRY_RUN=1
  result="$(restore_grub_files "$d")"
  [[ "$result" == *"would_run"*"etc-default-grub"*"/etc/default/grub"* ]]
  [[ "$result" != *"rm -rf /etc/default"* ]]
}

@test "verify_grub_restored requires binary, config, AND firmware entry" {
  esp="$BATS_TEST_TMPDIR/esp"
  mkdir -p "$esp/EFI/GRUB"
  : > "$esp/EFI/GRUB/grubx64.efi"
  cfg="$BATS_TEST_TMPDIR/grub.cfg"
  : > "$cfg"
  ebm="Boot0003* GRUB	HD(1,GPT,x)/File(\\EFI\\GRUB\\grubx64.efi)"
  run verify_grub_restored "$esp" "$ebm" "$cfg"
  [ "$status" -eq 0 ]
  # missing NVRAM entry
  run verify_grub_restored "$esp" "no grub here" "$cfg"
  [ "$status" -ne 0 ]
  # missing config
  run verify_grub_restored "$esp" "$ebm" "$BATS_TEST_TMPDIR/nope.cfg"
  [ "$status" -ne 0 ]
  # missing binary
  run verify_grub_restored "$BATS_TEST_TMPDIR/empty-esp" "$ebm" "$cfg"
  [ "$status" -ne 0 ]
}

@test "remove_limine previews packages, ESP files, and orphaned kernels under DRY_RUN" {
  esp="$BATS_TEST_TMPDIR/esp"
  mid=b7c2a46f0a084a7d89b7f96a4784b975
  mkdir -p "$esp/EFI/XeroLinux" "$esp/$mid/linux"
  : > "$esp/$mid/linux/vmlinuz-linux"
  DRY_RUN=1
  run remove_limine "$esp"
  [ "$status" -eq 0 ]
  [[ "$output" == *"pacman -Rns"* ]]
  [[ "$output" == *"rm -rf $esp/EFI/XeroLinux"* ]]
  [[ "$output" == *"rm -rf $esp/$mid"* ]]
}

@test "remove_limine removes EVERY matching NVRAM entry, not just the first (real incident regression)" {
  # Regression: a real revert left an orphaned Limine NVRAM entry pointing
  # at files remove_limine had already deleted, alongside the surviving
  # entry, and GRUB was unreachable - the device booted straight to BIOS.
  # Root cause: the original code piped through `head -1`, structurally
  # incapable of removing more than one match no matter how many exist.
  esp="$BATS_TEST_TMPDIR/esp"
  mkdir -p "$esp/EFI/XeroLinux"
  DRY_RUN=0
  # `efibootmgr` (bare) stubs the read-only query remove_limine uses to
  # find bootnums; run_cmd (not `efibootmgr` the bash function) is what
  # actually invokes deletion, since that call uses the absolute path
  # /usr/bin/efibootmgr, which bypasses a same-named function stub entirely.
  efibootmgr() {
    printf 'Boot0000* Windows Boot Manager\tHD(1,GPT,aaaa)/File(\\EFI\\Microsoft\\Boot\\bootmgfw.efi)\n'
    printf 'Boot0001* XeroLinux\tHD(1,GPT,aaaa)/File(\\EFI\\XeroLinux\\BOOTX64.EFI)\n'
    printf 'Boot0002* XeroLinux\tHD(1,GPT,aaaa)/File(\\EFI\\XeroLinux\\BOOTX64.EFI)\n'
  }
  run_cmd() { echo "RUN_CMD: $*"; }
  result="$(remove_limine "$esp" "")"
  [[ "$result" == *"RUN_CMD: /usr/bin/efibootmgr -b 0001 -B"* ]]
  [[ "$result" == *"RUN_CMD: /usr/bin/efibootmgr -b 0002 -B"* ]]
  [[ "$result" != *"-b 0000"* ]]
}

@test "remove_limine does NOT delete GRUB's own NVRAM entry even when it shares Limine's 'XeroLinux' label (real incident regression)" {
  # Root cause of a worse real incident: register_efi_boot_entry always
  # labels Limine's entry "XeroLinux", and grub_bootloader_id_from_backup
  # preserves whatever label the ORIGINAL GRUB install used - on a machine
  # set up by XeroLinux's own installer, that's very often ALSO
  # "XeroLinux". Matching Limine's entry by label text (rather than loader
  # path) meant this function's own "remove every match" fix (the previous
  # regression test above) ALSO deleted GRUB's freshly-created entry, since
  # it shares that label - leaving ZERO firmware boot entries and a device
  # that boots straight to firmware setup instead of GRUB.
  esp="$BATS_TEST_TMPDIR/esp"
  mkdir -p "$esp/EFI/XeroLinux"
  DRY_RUN=0
  efibootmgr() {
    printf 'Boot0000* XeroLinux\tHD(1,GPT,aaaa)/File(\\EFI\\XeroLinux\\BOOTX64.EFI)\n'
    printf 'Boot0001* XeroLinux\tHD(1,GPT,aaaa)/File(\\EFI\\opensuse\\grubx64.efi)\n'
  }
  run_cmd() { echo "RUN_CMD: $*"; }
  result="$(remove_limine "$esp" "")"
  [[ "$result" == *"RUN_CMD: /usr/bin/efibootmgr -b 0000 -B"* ]]
  [[ "$result" != *"-b 0001"* ]]
}

@test "promote_grub_boot_order puts GRUB's bootnum first, keeping every other existing entry" {
  efibootmgr_v='Boot0003* GRUB\tHD(1,GPT,aaaa)/File(\EFI\opensuse\grubx64.efi)'
  current_order='0001,0002,0003'
  run_cmd() { echo "RUN_CMD: $*"; }
  result="$(promote_grub_boot_order '/EFI/opensuse/grubx64.efi' "$efibootmgr_v" "$current_order")"
  [[ "$result" == *"RUN_CMD: /usr/bin/efibootmgr -o 0003,0001,0002"* ]]
}

@test "promote_grub_boot_order does nothing when GRUB is already first" {
  efibootmgr_v='Boot0001* GRUB\tHD(1,GPT,aaaa)/File(\EFI\opensuse\grubx64.efi)'
  current_order='0001,0002,0003'
  run_cmd() { echo "SHOULD_NOT_BE_CALLED"; }
  result="$(promote_grub_boot_order '/EFI/opensuse/grubx64.efi' "$efibootmgr_v" "$current_order")"
  [[ "$result" != *"SHOULD_NOT_BE_CALLED"* ]]
}

@test "promote_grub_boot_order does nothing when GRUB's NVRAM entry cannot be found" {
  run_cmd() { echo "SHOULD_NOT_BE_CALLED"; }
  result="$(promote_grub_boot_order '/EFI/opensuse/grubx64.efi' "" "0001,0002")"
  [[ "$result" != *"SHOULD_NOT_BE_CALLED"* ]]
}

@test "cmd_revert calls promote_grub_boot_order with GRUB's real bootloader-id path after removing Limine" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  grub_bootloader_id_from_backup() { echo "opensuse"; }
  promote_grub_boot_order() { echo "PROMOTE_CALLED_WITH: $*"; }
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *"PROMOTE_CALLED_WITH: /EFI/opensuse/grubx64.efi"* ]]
  [[ "$output" == *"Making sure GRUB boots first"* ]]
}

@test "cmd_revert refuses when no backup exists" {
  grub_backup_is_complete() { return 1; }
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"No pre-migration GRUB backup"* ]]
}

@test "cmd_revert refuses when Limine is not the active bootloader" {
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "grub"; }
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"Limine is not the active bootloader"* ]]
}

@test "cmd_revert refuses when Secure Boot is enabled (would leave unsigned GRUB)" {
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "enabled"; }
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"Secure Boot is enabled"* ]]
}

@test "cmd_revert does NOT remove Limine when GRUB verification fails" {
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  reinstall_grub_packages() { return 0; }
  restore_grub_files() { return 0; }
  verify_grub_restored() { return 1; }
  remove_limine() { echo "SHOULD_NOT_BE_CALLED"; }
  run_cmd() { emit_event "would_run" "info" "$*"; }
  DRY_RUN=0
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"could not be verified"* ]]
  [[ "$output" != *"SHOULD_NOT_BE_CALLED"* ]]
}

@test "cmd_revert runs the full ordered flow (packages -> restore config -> grub-install -> grub-mkconfig -> remove Limine) and finishes" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *"Reinstalling GRUB packages"* ]]
  [[ "$output" == *"Restoring your original GRUB configuration"* ]]
  [[ "$output" == *"grub-install --target=x86_64-efi --efi-directory=$BATS_TEST_TMPDIR/esp --bootloader-id=Xero-Linux --force --recheck"* ]]
  [[ "$output" == *"Generating GRUB configuration"* ]]
  [[ "$output" == *"grub-mkconfig -o /boot/grub/grub.cfg"* ]]
  [[ "$output" == *"Removing Limine"* ]]
  [[ "$output" == *"revert_done"* ]]
  # restore (config) happens before grub-install, since grub-install itself
  # reads /etc/default/grub at install time.
  [[ "$output" =~ "Restoring your original GRUB configuration".*"grub-install --target" ]]
}

@test "cmd_revert's final message is dry-run-aware: does not claim completion during a preview" {
  # Regression: the RevertDialog GUI runs `revert --dry-run` automatically
  # as its first, no-action-taken step, and the OLD unconditional "Revert
  # complete... reboot to use it" message showed up in that preview's own
  # log too - confusingly implying it had already happened before the user
  # ever clicked Apply Revert.
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"

  DRY_RUN=1
  run cmd_revert
  [[ "$output" == *"Clear to revert"* ]]
  [[ "$output" == *"press Apply Revert"* ]]
  [[ "$output" != *"Revert complete"* ]]
}

@test "cmd_revert's final message confirms completion for a real (non-dry-run) revert" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  run_cmd() { echo "RUN_CMD: $*"; }
  efibootmgr() { echo ""; }
  verify_grub_restored() { return 0; }

  DRY_RUN=0
  run cmd_revert
  [[ "$output" == *"Revert complete. GRUB is restored; reboot to use it."* ]]
  [[ "$output" != *"Clear to revert"* ]]
}

@test "cmd_revert reports a clear error and stops when grub-mkconfig fails" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  remove_limine() { echo "SHOULD_NOT_BE_CALLED"; }
  run_cmd() {
    [[ "$1" == "/usr/bin/grub-mkconfig" ]] && return 1
    return 0
  }
  DRY_RUN=0
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"grub-mkconfig failed"* ]]
  [[ "$output" == *"Limine has NOT been touched"* ]]
  [[ "$output" != *"SHOULD_NOT_BE_CALLED"* ]]
}

@test "cmd_revert runs a post-revert boot doctor check and includes it in the output" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  is_uefi() { return 0; }
  detect_partition_table() { return 0; }
  efibootmgr() { printf 'Boot0000* XeroLinux\tHD(1,GPT,aaaa,0x800,0x100000)/File(\\EFI\\XeroLinux\\BOOTX64.EFI)\n'; }
  export -f efibootmgr
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *"doctor_check"* ]]
  [[ "$output" == *"doctor_done"* ]]
  [[ "$output" == *"revert_done"* ]]
}

@test "cmd_revert still reports success even when the post-revert doctor check finds a problem" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp"
  run_boot_doctor_checks() { emit_event "doctor_done" "error" "simulated doctor failure"; return 1; }
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *"simulated doctor failure"* ]]
  [[ "$output" == *"revert_done"* ]]
}

@test "cmd_revert clears Limine's leftover UEFI fallback binary, not just the bootloader-id path" {
  # Regression test: migration also writes Limine's binary to the generic
  # EFI/Boot/BOOTX64.EFI fallback path (deploy_limine_to_esp in migrate.sh),
  # and remove_limine never cleans that path up. Without clearing it here
  # too, firmware falling back to that path after Limine's NVRAM entry is
  # removed loads Limine's now configless binary: an empty Limine menu, no
  # way to reach GRUB, even though GRUB's own NVRAM entry is present.
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp/EFI/Boot"
  : > "$BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI"
  detect_other_os() { echo ""; }
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" == *"Clearing Limine's leftover UEFI fallback binary"* ]]
  [[ "$output" == *"rm -f $BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI"* ]]
}

@test "cmd_revert does not touch the fallback path when nothing is there or a real non-Windows OS owns it" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp/EFI/Boot"
  : > "$BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI"
  detect_other_os() { echo "openSUSE Tumbleweed"; }
  DRY_RUN=1
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" != *"Clearing Limine's leftover UEFI fallback binary"* ]]
  [ -e "$BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI" ]

  detect_other_os() { echo ""; }
  rm "$BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI"
  run cmd_revert
  [ "$status" -eq 0 ]
  [[ "$output" != *"Clearing Limine's leftover UEFI fallback binary"* ]]
}

@test "cmd_revert aborts without touching Limine when clearing the fallback binary fails" {
  export XSB_BACKUP_DIR="$BATS_TEST_TMPDIR/bk"
  mkdir -p "$XSB_BACKUP_DIR"
  printf 'grub\n' > "$XSB_BACKUP_DIR/packages.txt"
  grub_backup_is_complete() { return 0; }
  detect_bootloader() { echo "limine"; }
  detect_secureboot_state() { echo "disabled"; }
  find_esp_mountpoint() { echo "$BATS_TEST_TMPDIR/esp"; }
  mkdir -p "$BATS_TEST_TMPDIR/esp/EFI/Boot"
  : > "$BATS_TEST_TMPDIR/esp/EFI/Boot/BOOTX64.EFI"
  detect_other_os() { echo ""; }
  remove_limine() { echo "SHOULD_NOT_BE_CALLED"; }
  run_cmd() {
    if [[ "$*" == *"rm -f"*"BOOTX64.EFI"* ]]; then
      return 1
    fi
    emit_event "would_run" "info" "$*"
  }
  DRY_RUN=0
  run cmd_revert
  [ "$status" -ne 0 ]
  [[ "$output" == *"Failed to clear Limine's leftover fallback binary"* ]]
  [[ "$output" != *"SHOULD_NOT_BE_CALLED"* ]]
}
