#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

chainload_loader_path_for_os() {
    local os_label="$1"
    case "$os_label" in
        *[Ww]indows*) printf '/EFI/Microsoft/Boot/bootmgfw.efi' ;;
        *) printf '/EFI/Boot/bootx64.efi' ;;
    esac
}

# Builds ONLY the chainload stanzas for detected other-OSes, to be appended
# to <esp_mountpoint>/limine.conf (limine.conf lives on the ESP itself,
# alongside the Limine EFI binary; see limine-mkinitcpio's UEFI convention).
# The timeout:/default_entry: header and the kernel
# entries for XeroLinux itself are generated by limine-mkinitcpio-hook from
# /etc/default/limine (see write_limine_defaults), not by this function, so
# this must never emit anything else or it will duplicate the hook's output.
build_limine_conf() {
    local other_os_list="${1-}"
    local -a lines=()
    if [[ -n "$other_os_list" ]]; then
        local os_label loader_path
        while IFS= read -r os_label; do
            [[ -z "$os_label" ]] && continue
            loader_path="$(chainload_loader_path_for_os "$os_label")"
            [[ ${#lines[@]} -gt 0 ]] && lines+=("")
            lines+=("/$os_label" "    protocol: efi_chainload" "    path: boot():${loader_path}")
        done <<< "$other_os_list"
    fi
    if [[ ${#lines[@]} -gt 0 ]]; then
        printf '%s\n' "${lines[@]}"
    fi
}

resolve_root_cmdline_params() {
    local luks="$1" mkinitcpio_hook="$2" root_uuid="$3" crypttab_content="${4-$(cat /etc/crypttab 2>/dev/null)}"
    # root_source/root_fstype/root_options describe the CURRENTLY MOUNTED
    # root filesystem. This tool only ever runs on a live, already-booted
    # system, so findmnt's live view of / is a reliable ground truth for
    # both the LVM-on-LUKS and btrfs-subvolume detection below - regardless
    # of naming conventions or fstab formatting quirks.
    local root_source="${5-$(findmnt -no SOURCE / 2>/dev/null)}"
    local root_fstype="${6-$(findmnt -no FSTYPE / 2>/dev/null)}"
    local root_options="${7-$(findmnt -no OPTIONS / 2>/dev/null)}"

    # Bug 3: btrfs subvolume root. grub-mkconfig would read /etc/fstab and
    # emit rootflags=subvol=<name>; this tool never read fstab, so mkinitcpio
    # couldn't find the correct subvolume to mount as root. findmnt -no
    # OPTIONS / is used instead of parsing /etc/fstab directly since it
    # reflects the live mount reality. Applies independent of LUKS (both
    # branches below fall through to this).
    # ASSUMPTION: the kernel/findmnt report subvol= with a leading "/"
    # (subvolume path from the top of the btrfs tree, e.g. "subvol=/@"),
    # while /etc/fstab conventionally omits it (e.g. "subvol=@"). Both forms
    # are accepted identically by the kernel/mount, but the leading "/" is
    # stripped here to match the form GRUB would have emitted from fstab.
    local rootflags=""
    if [[ "$root_fstype" == "btrfs" ]]; then
        # Combined single-statement local+assignment (see the LVM-on-LUKS
        # note below for why): grep legitimately exits non-zero when
        # root_options has no subvol= at all (a plausible top-level-mount
        # scenario), and a split `local subvol_opt` / `subvol_opt="$(...)"`
        # would not reliably mask that under set -e in every calling
        # context. The trailing `|| true` makes "no subvol= match" an
        # intentional, handled empty-string result instead.
        local subvol_opt="$(grep -oE 'subvol=[^,]+' <<< "$root_options" | head -1 || true)"
        if [[ -n "$subvol_opt" ]]; then
            # A bare "subvol=/" (the actual top-level subvolume, no named
            # subvolume) strips down to an empty string here - that's the
            # default mount and needs no rootflags= at all, so only append
            # when a real (named) subvolume remains after stripping.
            local subvol_name="${subvol_opt#subvol=/}"
            [[ -n "$subvol_name" ]] && rootflags=" rootflags=subvol=${subvol_name}"
        fi
    fi

    if [[ "$luks" != "true" ]]; then
        printf 'root=UUID=%s%s' "$root_uuid" "$rootflags"
        return
    fi

    # Bug 2: multiple crypttab entries (e.g. encrypted swap listed above the
    # encrypted root). Prefer the entry whose mapper name matches the
    # currently-mounted root device (root_source) over blindly taking the
    # first non-comment line.
    local root_mapper_name=""
    [[ -n "$root_source" ]] && root_mapper_name="$(basename "$root_source")"

    # Bug 2 (crypttab entry selection): a direct mapper-name match handles
    # plain (non-LVM) LUKS root correctly. It deliberately does NOT handle
    # LVM-on-LUKS (see Bug 1 below): root_mapper_name there is the LV's
    # basename (e.g. "vgname-root"), which never matches a crypttab entry
    # naming the raw LUKS container, so this always falls through.
    local crypt_line=""
    if [[ -n "$root_mapper_name" ]]; then
        crypt_line="$(grep -vE '^[[:space:]]*(#|$)' <<< "$crypttab_content" \
            | awk -v m="$root_mapper_name" '$1 == m' | head -1)"
    fi

    if [[ -z "$crypt_line" ]]; then
        # No direct mapper-name match: this is the LVM-on-LUKS signature.
        # Rather than blindly falling back to head -1 (which, with multiple
        # crypttab entries - e.g. an encrypted swap partition listed before
        # the LVM-bearing LUKS container - can select a completely unrelated
        # entry), determine the live root LV's volume group and select the
        # crypttab entry whose LUKS mapper is itself a PV in that SAME VG.
        # root_lv_vg's default is combined into a single `local x="$(cmd)"`
        # statement for the same set -e safety reason documented below for
        # pvs_output/lv_uuid: lvs legitimately exits non-zero when
        # root_source isn't an LV (the common plain-LUKS/no-LVM case).
        local root_lv_vg="${10-$(lvs --noheadings -o vg_name "$root_source" 2>/dev/null | tr -d '[:space:]')}"
        if [[ -n "$root_lv_vg" ]]; then
            local candidate_line
            while IFS= read -r candidate_line; do
                [[ -z "$candidate_line" ]] && continue
                local candidate_mapper="$(awk '{print $1}' <<< "$candidate_line")"
                local candidate_vg="$(pvs --noheadings -o vg_name "/dev/mapper/${candidate_mapper}" 2>/dev/null | tr -d '[:space:]')"
                if [[ -n "$candidate_vg" && "$candidate_vg" == "$root_lv_vg" ]]; then
                    crypt_line="$candidate_line"
                    break
                fi
            done < <(grep -vE '^[[:space:]]*(#|$)' <<< "$crypttab_content")
        fi
    fi

    if [[ -z "$crypt_line" ]]; then
        # Final fallback: nothing matched by either the direct mapper-name
        # method or the VG-matching method above - a genuinely
        # ambiguous/unusual setup. Same spirit as before, now a true last
        # resort rather than the primary path for the LVM-on-LUKS case.
        crypt_line="$(grep -vE '^[[:space:]]*(#|$)' <<< "$crypttab_content" | head -1)"
    fi

    local mapper_name="$(awk '{print $1}' <<< "$crypt_line")"
    local luks_uuid="$(awk '{print $2}' <<< "$crypt_line" | sed -E 's#^(UUID=|/dev/disk/by-uuid/)##')"

    # Bug 1: LVM-on-LUKS. Calamares's "erase disk and encrypt" flow creates
    # LUKS -> LVM PV -> VG -> LVs, one of which is the actual root
    # filesystem - NOT the raw LUKS mapper device directly. Detect this by
    # checking whether the opened LUKS mapper is itself an LVM PV; if so,
    # resolve root= to the real root LV's UUID (via the live root_source,
    # which - since this only runs on an already-booted system - already IS
    # that LV's device path) instead of the raw LUKS mapper.
    # NOTE: these two defaults are deliberately written as single combined
    # `local x="${N-$(cmd)}"` statements (matching crypttab_content above),
    # not split across a `local x` declaration and a separate assignment.
    # Under this project's `set -euo pipefail` entrypoint, a split
    # assignment's exit status is that of the failing command substitution
    # itself and WOULD abort the whole script (e.g. pvs legitimately exits
    # non-zero for a non-PV device - the common plain-LUKS case); combined
    # with `local`, the exit status is `local`'s own (successful), masking
    # the inner command's failure so a non-PV/non-existent device is safely
    # treated as "empty output" instead of crashing cmd_migrate.
    local pvs_output="${8-$(pvs --noheadings -o vg_name "/dev/mapper/${mapper_name}" 2>/dev/null | head -1)}"

    local root_dev_part
    if [[ -n "$pvs_output" ]]; then
        local lv_uuid="${9-$(blkid -s UUID -o value "$root_source" 2>/dev/null)}"
        root_dev_part="root=UUID=${lv_uuid}"
    else
        # Not an LVM PV: plain LUKS-encrypted root. Preserve exact prior
        # behavior unchanged (this is the common case).
        root_dev_part="root=/dev/mapper/${mapper_name}"
    fi

    if [[ "$mkinitcpio_hook" == "sd-encrypt" ]]; then
        printf 'rd.luks.name=%s=%s %s%s' "$luks_uuid" "$mapper_name" "$root_dev_part" "$rootflags"
    else
        printf 'cryptdevice=UUID=%s:%s %s%s' "$luks_uuid" "$mapper_name" "$root_dev_part" "$rootflags"
    fi
}

resolve_grub_extra_params() {
    local grub_defaults_content="${1-$(cat /etc/default/grub 2>/dev/null)}"
    local line value
    line="$(grep -E '^GRUB_CMDLINE_LINUX_DEFAULT=' <<< "$grub_defaults_content" | tail -1)"
    if [[ -z "$line" ]]; then
        printf 'quiet nowatchdog loglevel=3'
        return
    fi
    value="${line#GRUB_CMDLINE_LINUX_DEFAULT=}"
    value="${value%\"}"
    value="${value#\"}"
    value="${value%\'}"
    value="${value#\'}"
    if [[ -z "$value" ]]; then
        printf 'quiet nowatchdog loglevel=3'
    else
        printf '%s' "$value"
    fi
}

build_limine_defaults_content() {
    local root_cmdline_params="$1" grub_extra_params="$2"
    printf 'KERNEL_CMDLINE[default]="%s %s"\n' "$grub_extra_params" "$root_cmdline_params"
}

write_limine_defaults() {
    local path="${1-/etc/default/limine}" root_cmdline_params="$2" grub_extra_params="${3-quiet nowatchdog loglevel=3}"
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        emit_event "would_run" "info" "write $path"
        return 0
    fi
    build_limine_defaults_content "$root_cmdline_params" "$grub_extra_params" > "$path"
}

install_limine_packages() {
    run_cmd /usr/bin/pacman -S --noconfirm --needed limine limine-mkinitcpio-hook
}

resolve_esp_disk_and_part() {
    local esp_source="${1-$(findmnt -no SOURCE /boot/efi 2>/dev/null)}"
    local parent_disk part_num
    parent_disk="$(lsblk -no PKNAME "$esp_source" 2>/dev/null)"
    part_num="$(lsblk -no PARTN "$esp_source" 2>/dev/null)"
    printf '/dev/%s %s' "$parent_disk" "$part_num"
}

deploy_limine_to_esp() {
    local esp_mountpoint="${1-/boot/efi}" skip_fallback="${2-0}"
    run_cmd /usr/bin/mkdir -p "${esp_mountpoint}/EFI/XeroLinux"
    run_cmd /usr/bin/cp /usr/share/limine/BOOTX64.EFI "${esp_mountpoint}/EFI/XeroLinux/BOOTX64.EFI"
    # Also overwrite the generic UEFI "removable media" fallback path
    # (\EFI\Boot\BOOTX64.EFI). GRUB was originally installed there too
    # (XeroLinux's Calamares bootloader.conf sets installEFIFallback: true),
    # and firmware can auto-create boot options (e.g. "UEFI Misc Device")
    # pointing at this generic path independent of any NVRAM entry we
    # control. remove_grub only deletes GRUB's named-path NVRAM entry, so
    # without this, firmware fallback/auto-boot could still land on GRUB's
    # leftover binary here after migration. Directory casing matches the
    # existing /EFI/Boot/ convention used by chainload_loader_path_for_os;
    # filename casing matches the BOOTX64.EFI we already deploy above.
    #
    # skip_fallback=1 opts out of this overwrite: chainload_loader_path_for_os
    # falls back to this same generic path as its best-effort guess for any
    # detected non-Windows other-OS (since detect_other_os only sees NVRAM
    # boot-entry labels, not real ESP paths). Overwriting it unconditionally
    # would clobber that other OS's actual bootable binary with Limine's own,
    # breaking its dual-boot chainload stanza. The caller decides skip_fallback
    # based on whether such an other-OS was detected.
    if [[ "$skip_fallback" != "1" ]]; then
        run_cmd /usr/bin/mkdir -p "${esp_mountpoint}/EFI/Boot"
        run_cmd /usr/bin/cp /usr/share/limine/BOOTX64.EFI "${esp_mountpoint}/EFI/Boot/BOOTX64.EFI"
    fi
}

verify_limine_deployed() {
    local esp_mountpoint="${1-/boot/efi}"
    [[ -f "${esp_mountpoint}/EFI/XeroLinux/BOOTX64.EFI" ]]
}

verify_limine_conf_has_kernel_entry() {
    local path="${1-/boot/efi/limine.conf}"
    grep -q 'protocol:[[:space:]]*linux' "$path" 2>/dev/null
}

register_efi_boot_entry() {
    local esp_disk="$1" esp_part_num="$2"
    if verify_limine_entry; then
        emit_event "migrate_step" "info" "Limine EFI boot entry already registered, skipping."
        return 0
    fi
    run_cmd /usr/bin/efibootmgr --create --disk "$esp_disk" --part "$esp_part_num" \
        --label "XeroLinux" --loader '\EFI\XeroLinux\BOOTX64.EFI'
}

verify_limine_entry() {
    local efibootmgr_output="${1-$(efibootmgr -v 2>/dev/null)}"
    grep -qi 'XeroLinux.*BOOTX64\.EFI' <<< "$efibootmgr_output"
}

find_grub_efi_bootnum() {
    local efibootmgr_output="${1-$(efibootmgr -v 2>/dev/null)}"
    # "No GRUB entry found" is a normal outcome, not a failure: the leading
    # grep legitimately exits non-zero on no match, which would otherwise
    # trip `pipefail` in callers running under `set -euo pipefail` and kill
    # the script mid-remove_grub. Always return success; an empty result
    # means "nothing to delete".
    grep -iE 'XeroLinux.*grubx64\.efi' <<< "$efibootmgr_output" | grep -oE '^Boot[0-9A-Fa-f]{4}' | head -1 | sed 's/^Boot//' || true
}

remove_grub() {
    run_cmd /usr/bin/pacman -Rns --noconfirm grub grub-hooks update-grub os-prober
    run_cmd /usr/bin/rm -rf /boot/grub
    run_cmd /usr/bin/rm -f /etc/default/grub
    local grub_bootnum
    grub_bootnum="$(find_grub_efi_bootnum)"
    if [[ -n "$grub_bootnum" ]]; then
        run_cmd /usr/bin/efibootmgr -b "$grub_bootnum" -B
    fi
}

write_limine_conf() {
    local path="${1-/boot/efi/limine.conf}" other_os_list="${2-}"
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        emit_event "would_run" "info" "append chainload entries to $path"
        return 0
    fi
    if [[ -n "$other_os_list" ]]; then
        build_limine_conf "$other_os_list" >> "$path"
    fi
}

run_limine_mkinitcpio() {
    local bin_path="${1-/usr/bin/limine-mkinitcpio}"
    [[ -x "$bin_path" ]] || return 1
    run_cmd "$bin_path"
}

cmd_migrate() {
    if [[ "$(detect_bootloader)" != "grub" ]]; then
        emit_event "error" "error" "GRUB not detected. Nothing to migrate."
        return 1
    fi

    if [[ "$(detect_secureboot_state)" == "enabled" ]]; then
        emit_event "error" "error" "Secure Boot is already enabled in firmware. Migrating now would leave an unsigned, unbootable Limine after reboot. Reboot into UEFI firmware settings and disable Secure Boot first - it can be safely re-enabled after migration completes, once Limine is signed."
        return 1
    fi

    local esp_mountpoint
    esp_mountpoint="$(find_esp_mountpoint)" || {
        emit_event "error" "error" "No EFI system partition found. Aborting before any changes."
        return 1
    }

    emit_event "migrate_step" "info" "Installing Limine and limine-mkinitcpio-hook"
    install_limine_packages || {
        emit_event "error" "error" "Failed to install Limine packages. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Configuring /etc/default/limine"
    local luks="false"
    detect_luks_root && luks="true"
    local mkinitcpio_hook root_uuid root_source root_fstype root_options crypttab_content
    local root_cmdline_params grub_extra_params
    mkinitcpio_hook="$(detect_mkinitcpio_hook_family)"
    root_uuid="$(findmnt -no UUID / 2>/dev/null)" || true
    root_source="$(findmnt -no SOURCE / 2>/dev/null)" || true
    root_fstype="$(findmnt -no FSTYPE / 2>/dev/null)" || true
    root_options="$(findmnt -no OPTIONS / 2>/dev/null)" || true
    crypttab_content="$(cat /etc/crypttab 2>/dev/null)" || true
    root_cmdline_params="$(resolve_root_cmdline_params "$luks" "$mkinitcpio_hook" "$root_uuid" \
        "$crypttab_content" "$root_source" "$root_fstype" "$root_options")"
    grub_extra_params="$(resolve_grub_extra_params)"
    write_limine_defaults "/etc/default/limine" "$root_cmdline_params" "$grub_extra_params" || {
        emit_event "error" "error" "Failed to write /etc/default/limine. GRUB has NOT been touched."
        return 1
    }

    local other_os
    other_os="$(detect_other_os)"
    local skip_fallback=0
    has_non_windows_other_os "$other_os" && skip_fallback=1
    if [[ "$skip_fallback" == "1" ]]; then
        emit_event "migrate_step" "info" "Skipping generic EFI fallback path deploy: a non-Windows dual-boot OS may rely on it."
    fi

    emit_event "migrate_step" "info" "Deploying Limine to the EFI system partition"
    deploy_limine_to_esp "$esp_mountpoint" "$skip_fallback" || {
        emit_event "error" "error" "Failed to deploy Limine to the ESP. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Registering Limine EFI boot entry"
    local esp_disk esp_part_num
    read -r esp_disk esp_part_num <<< "$(resolve_esp_disk_and_part)"
    register_efi_boot_entry "$esp_disk" "$esp_part_num" || {
        emit_event "error" "error" "Failed to register Limine's EFI boot entry. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Regenerating initramfs"
    run_cmd /usr/bin/mkinitcpio -P || {
        emit_event "error" "error" "Failed to regenerate initramfs. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Regenerating Limine boot entries"
    run_limine_mkinitcpio || {
        emit_event "error" "error" "Failed to regenerate Limine boot entries via limine-mkinitcpio. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Adding chainload entries for other operating systems"
    write_limine_conf "${esp_mountpoint}/limine.conf" "$other_os" || {
        emit_event "error" "error" "Failed to write chainload entries to ${esp_mountpoint}/limine.conf. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Verifying Limine EFI boot entry, ESP deployment, and limine.conf kernel entry"
    if ! verify_limine_entry || ! verify_limine_deployed "$esp_mountpoint" || ! verify_limine_conf_has_kernel_entry "${esp_mountpoint}/limine.conf"; then
        emit_event "error" "error" "Limine's EFI boot entry, ESP deployment, or limine.conf kernel entry could not be verified. GRUB has NOT been removed; your system is still bootable via GRUB."
        return 1
    fi

    emit_event "migrate_step" "info" "Removing GRUB"
    remove_grub

    emit_event "migrate_done" "info" "Migration to Limine complete."
}

build_limine_splash_header() {
    printf '### Theme\nwallpaper: boot():/splash.png\n\n'
}

# Idempotently (re)writes the ### Theme section at the top of <path> so it
# contains only the wallpaper directive. Any prior ### Theme section is
# fully replaced rather than appended alongside - this matters for systems
# migrated before this feature existed, whose limine.conf may still carry
# the old palette-based ### Theme block (term_palette/term_background/etc)
# that this tool used to write; those stale color directives must not be
# left sitting next to the new wallpaper line.
write_limine_splash() {
    local path="$1"
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        emit_event "would_run" "info" "write splash wallpaper header to $path"
        return 0
    fi
    local tmp
    tmp="$(mktemp)"
    awk '
        /^### Theme/ { skip=1; next }
        skip && (/^###/ || NF==0) { skip=0 }
        skip { next }
        { print }
    ' "$path" > "$tmp"
    { build_limine_splash_header; cat "$tmp"; } > "${path}.new"
    rm -f "$tmp"
    chmod --reference="$path" "${path}.new" 2>/dev/null || true
    mv "${path}.new" "$path"
}

verify_wallpaper_source_exists() {
    local wallpaper_path="${1-/usr/share/wallpapers/Xero-Plasma4.png}"
    [[ -f "$wallpaper_path" ]]
}

cmd_apply_splash() {
    if [[ "$(detect_bootloader)" != "limine" ]]; then
        emit_event "error" "error" "Limine is not the active bootloader. Nothing to splash."
        return 1
    fi
    local esp_mountpoint
    esp_mountpoint="$(find_esp_mountpoint)" || {
        emit_event "error" "error" "No EFI system partition found."
        return 1
    }
    if [[ ! -f "${esp_mountpoint}/limine.conf" ]]; then
        emit_event "error" "error" "${esp_mountpoint}/limine.conf not found."
        return 1
    fi
    if ! verify_wallpaper_source_exists; then
        emit_event "error" "error" "XeroLinux wallpaper not found at /usr/share/wallpapers/Xero-Plasma4.png."
        return 1
    fi
    emit_event "splash_step" "info" "Copying boot splash wallpaper"
    run_cmd /usr/bin/cp /usr/share/wallpapers/Xero-Plasma4.png "${esp_mountpoint}/splash.png" || {
        emit_event "error" "error" "Failed to copy splash wallpaper."
        return 1
    }
    write_limine_splash "${esp_mountpoint}/limine.conf" || {
        emit_event "error" "error" "Failed to update ${esp_mountpoint}/limine.conf with splash wallpaper."
        return 1
    }
    emit_event "apply_splash_done" "info" "Boot splash applied to ${esp_mountpoint}/limine.conf."
}
