#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later

chainload_loader_path_for_os() {
    local os_label="$1"
    case "$os_label" in
        *[Ww]indows*) printf '/EFI/Microsoft/Boot/bootmgfw.efi' ;;
        *) printf '/EFI/Boot/bootx64.efi' ;;
    esac
}

# Builds ONLY the chainload stanzas for detected other-OSes, to be appended
# to <esp_mountpoint>/limine.conf (limine.conf lives on the ESP itself,
# alongside the Limine EFI binary; see limine-mkinitcpio's UEFI convention).
# The timeout:/default_entry: header and the kernel
# entries for XeroLinux itself are generated by limine-mkinitcpio-hook from
# /etc/default/limine (see write_limine_defaults), not by this function, so
# this must never emit anything else or it will duplicate the hook's output.
build_limine_conf() {
    local other_os_list="${1-}"
    local -a lines=()
    if [[ -n "$other_os_list" ]]; then
        local os_label loader_path
        while IFS= read -r os_label; do
            [[ -z "$os_label" ]] && continue
            loader_path="$(chainload_loader_path_for_os "$os_label")"
            [[ ${#lines[@]} -gt 0 ]] && lines+=("")
            lines+=("/$os_label" "    protocol: efi_chainload" "    path: boot():${loader_path}")
        done <<< "$other_os_list"
    fi
    if [[ ${#lines[@]} -gt 0 ]]; then
        printf '%s\n' "${lines[@]}"
    fi
}

build_limine_theme_header() {
    cat <<'EOF'
### Theme
term_palette: 232136;eb6f92;9ccfd8;f6c177;3e8fb0;c4a7e7;9ccfd8;e0def4
term_palette_bright: 6e6a86;eb6f92;9ccfd8;f6c177;3e8fb0;c4a7e7;9ccfd8;e0def4
term_background: 00232136
term_foreground: e0def4
term_background_bright: 6e6a86
term_foreground_bright: e0def4
EOF
}

resolve_root_cmdline_params() {
    local luks="$1" mkinitcpio_hook="$2" root_uuid="$3" crypttab_content="${4-$(cat /etc/crypttab 2>/dev/null)}"
    if [[ "$luks" != "true" ]]; then
        printf 'root=UUID=%s' "$root_uuid"
        return
    fi
    local crypt_line mapper_name luks_uuid
    crypt_line="$(grep -vE '^[[:space:]]*(#|$)' <<< "$crypttab_content" | head -1)"
    mapper_name="$(awk '{print $1}' <<< "$crypt_line")"
    luks_uuid="$(awk '{print $2}' <<< "$crypt_line" | sed -E 's#^(UUID=|/dev/disk/by-uuid/)##')"
    if [[ "$mkinitcpio_hook" == "sd-encrypt" ]]; then
        printf 'rd.luks.name=%s=%s root=/dev/mapper/%s' "$luks_uuid" "$mapper_name" "$mapper_name"
    else
        printf 'cryptdevice=UUID=%s:%s root=/dev/mapper/%s' "$luks_uuid" "$mapper_name" "$mapper_name"
    fi
}

build_limine_defaults_content() {
    local root_cmdline_params="$1"
    printf 'KERNEL_CMDLINE[default]="quiet nowatchdog loglevel=3 %s"\n' "$root_cmdline_params"
}

write_limine_defaults() {
    local path="${1-/etc/default/limine}" root_cmdline_params="$2"
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        emit_event "would_run" "info" "write $path"
        return 0
    fi
    build_limine_defaults_content "$root_cmdline_params" > "$path"
}

install_limine_packages() {
    run_cmd /usr/bin/pacman -S --noconfirm --needed limine limine-mkinitcpio-hook
}

resolve_esp_disk_and_part() {
    local esp_source="${1-$(findmnt -no SOURCE /boot/efi 2>/dev/null)}"
    local parent_disk part_num
    parent_disk="$(lsblk -no PKNAME "$esp_source" 2>/dev/null)"
    part_num="$(lsblk -no PARTN "$esp_source" 2>/dev/null)"
    printf '/dev/%s %s' "$parent_disk" "$part_num"
}

deploy_limine_to_esp() {
    local esp_mountpoint="${1-/boot/efi}" skip_fallback="${2-0}"
    run_cmd /usr/bin/mkdir -p "${esp_mountpoint}/EFI/XeroLinux"
    run_cmd /usr/bin/cp /usr/share/limine/BOOTX64.EFI "${esp_mountpoint}/EFI/XeroLinux/BOOTX64.EFI"
    # Also overwrite the generic UEFI "removable media" fallback path
    # (\EFI\Boot\BOOTX64.EFI). GRUB was originally installed there too
    # (XeroLinux's Calamares bootloader.conf sets installEFIFallback: true),
    # and firmware can auto-create boot options (e.g. "UEFI Misc Device")
    # pointing at this generic path independent of any NVRAM entry we
    # control. remove_grub only deletes GRUB's named-path NVRAM entry, so
    # without this, firmware fallback/auto-boot could still land on GRUB's
    # leftover binary here after migration. Directory casing matches the
    # existing /EFI/Boot/ convention used by chainload_loader_path_for_os;
    # filename casing matches the BOOTX64.EFI we already deploy above.
    #
    # skip_fallback=1 opts out of this overwrite: chainload_loader_path_for_os
    # falls back to this same generic path as its best-effort guess for any
    # detected non-Windows other-OS (since detect_other_os only sees NVRAM
    # boot-entry labels, not real ESP paths). Overwriting it unconditionally
    # would clobber that other OS's actual bootable binary with Limine's own,
    # breaking its dual-boot chainload stanza. The caller decides skip_fallback
    # based on whether such an other-OS was detected.
    if [[ "$skip_fallback" != "1" ]]; then
        run_cmd /usr/bin/mkdir -p "${esp_mountpoint}/EFI/Boot"
        run_cmd /usr/bin/cp /usr/share/limine/BOOTX64.EFI "${esp_mountpoint}/EFI/Boot/BOOTX64.EFI"
    fi
}

verify_limine_deployed() {
    local esp_mountpoint="${1-/boot/efi}"
    [[ -f "${esp_mountpoint}/EFI/XeroLinux/BOOTX64.EFI" ]]
}

verify_limine_conf_has_kernel_entry() {
    local path="${1-/boot/efi/limine.conf}"
    grep -q 'protocol:[[:space:]]*linux' "$path" 2>/dev/null
}

register_efi_boot_entry() {
    local esp_disk="$1" esp_part_num="$2"
    if verify_limine_entry; then
        emit_event "migrate_step" "info" "Limine EFI boot entry already registered, skipping."
        return 0
    fi
    run_cmd /usr/bin/efibootmgr --create --disk "$esp_disk" --part "$esp_part_num" \
        --label "XeroLinux" --loader '\EFI\XeroLinux\BOOTX64.EFI'
}

verify_limine_entry() {
    local efibootmgr_output="${1-$(efibootmgr -v 2>/dev/null)}"
    grep -qi 'XeroLinux.*BOOTX64\.EFI' <<< "$efibootmgr_output"
}

find_grub_efi_bootnum() {
    local efibootmgr_output="${1-$(efibootmgr -v 2>/dev/null)}"
    # "No GRUB entry found" is a normal outcome, not a failure: the leading
    # grep legitimately exits non-zero on no match, which would otherwise
    # trip `pipefail` in callers running under `set -euo pipefail` and kill
    # the script mid-remove_grub. Always return success; an empty result
    # means "nothing to delete".
    grep -iE 'XeroLinux.*grubx64\.efi' <<< "$efibootmgr_output" | grep -oE '^Boot[0-9A-Fa-f]{4}' | head -1 | sed 's/^Boot//' || true
}

remove_grub() {
    run_cmd /usr/bin/pacman -Rns --noconfirm grub grub-hooks update-grub os-prober
    run_cmd /usr/bin/rm -rf /boot/grub
    run_cmd /usr/bin/rm -f /etc/default/grub
    local grub_bootnum
    grub_bootnum="$(find_grub_efi_bootnum)"
    if [[ -n "$grub_bootnum" ]]; then
        run_cmd /usr/bin/efibootmgr -b "$grub_bootnum" -B
    fi
}

write_limine_conf() {
    local path="${1-/boot/efi/limine.conf}" other_os_list="${2-}"
    if [[ "${DRY_RUN:-0}" == "1" ]]; then
        emit_event "would_run" "info" "prepend theme header and append chainload entries to $path"
        return 0
    fi
    if ! grep -q '^### Theme$' "$path" 2>/dev/null; then
        local tmp
        tmp="$(mktemp "${path}.XXXXXX" 2>/dev/null || mktemp)"
        build_limine_theme_header > "$tmp"
        printf '\n' >> "$tmp"
        cat "$path" >> "$tmp" 2>/dev/null
        chmod --reference="$path" "$tmp" 2>/dev/null || true
        mv "$tmp" "$path"
    fi
    if [[ -n "$other_os_list" ]]; then
        build_limine_conf "$other_os_list" >> "$path"
    fi
}

run_limine_mkinitcpio() {
    local bin_path="${1-/usr/bin/limine-mkinitcpio}"
    [[ -x "$bin_path" ]] || return 1
    run_cmd "$bin_path"
}

cmd_migrate() {
    if [[ "$(detect_bootloader)" != "grub" ]]; then
        emit_event "error" "error" "GRUB not detected. Nothing to migrate."
        return 1
    fi

    if [[ "$(detect_secureboot_state)" == "enabled" ]]; then
        emit_event "error" "error" "Secure Boot is already enabled in firmware. Migrating now would leave an unsigned, unbootable Limine after reboot. Reboot into UEFI firmware settings and disable Secure Boot first - it can be safely re-enabled after migration completes, once Limine is signed."
        return 1
    fi

    local esp_mountpoint
    esp_mountpoint="$(find_esp_mountpoint)" || {
        emit_event "error" "error" "No EFI system partition found. Aborting before any changes."
        return 1
    }

    emit_event "migrate_step" "info" "Installing Limine and limine-mkinitcpio-hook"
    install_limine_packages || {
        emit_event "error" "error" "Failed to install Limine packages. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Configuring /etc/default/limine"
    local luks="false"
    detect_luks_root && luks="true"
    local mkinitcpio_hook root_uuid root_cmdline_params
    mkinitcpio_hook="$(detect_mkinitcpio_hook_family)"
    root_uuid="$(findmnt -no UUID / 2>/dev/null)" || true
    root_cmdline_params="$(resolve_root_cmdline_params "$luks" "$mkinitcpio_hook" "$root_uuid")"
    write_limine_defaults "/etc/default/limine" "$root_cmdline_params" || {
        emit_event "error" "error" "Failed to write /etc/default/limine. GRUB has NOT been touched."
        return 1
    }

    local other_os
    other_os="$(detect_other_os)"
    local skip_fallback=0
    has_non_windows_other_os "$other_os" && skip_fallback=1
    if [[ "$skip_fallback" == "1" ]]; then
        emit_event "migrate_step" "info" "Skipping generic EFI fallback path deploy: a non-Windows dual-boot OS may rely on it."
    fi

    emit_event "migrate_step" "info" "Deploying Limine to the EFI system partition"
    deploy_limine_to_esp "$esp_mountpoint" "$skip_fallback" || {
        emit_event "error" "error" "Failed to deploy Limine to the ESP. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Registering Limine EFI boot entry"
    local esp_disk esp_part_num
    read -r esp_disk esp_part_num <<< "$(resolve_esp_disk_and_part)"
    register_efi_boot_entry "$esp_disk" "$esp_part_num" || {
        emit_event "error" "error" "Failed to register Limine's EFI boot entry. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Regenerating initramfs"
    run_cmd /usr/bin/mkinitcpio -P || {
        emit_event "error" "error" "Failed to regenerate initramfs. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Regenerating Limine boot entries"
    run_limine_mkinitcpio || {
        emit_event "error" "error" "Failed to regenerate Limine boot entries via limine-mkinitcpio. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Adding chainload entries for other operating systems"
    write_limine_conf "${esp_mountpoint}/limine.conf" "$other_os" || {
        emit_event "error" "error" "Failed to write chainload entries to ${esp_mountpoint}/limine.conf. GRUB has NOT been touched."
        return 1
    }

    emit_event "migrate_step" "info" "Verifying Limine EFI boot entry, ESP deployment, and limine.conf kernel entry"
    if ! verify_limine_entry || ! verify_limine_deployed "$esp_mountpoint" || ! verify_limine_conf_has_kernel_entry "${esp_mountpoint}/limine.conf"; then
        emit_event "error" "error" "Limine's EFI boot entry, ESP deployment, or limine.conf kernel entry could not be verified. GRUB has NOT been removed; your system is still bootable via GRUB."
        return 1
    fi

    emit_event "migrate_step" "info" "Removing GRUB"
    remove_grub

    emit_event "migrate_done" "info" "Migration to Limine complete."
}

cmd_apply_theme() {
    if [[ "$(detect_bootloader)" != "limine" ]]; then
        emit_event "error" "error" "Limine is not the active bootloader. Nothing to theme."
        return 1
    fi
    local esp_mountpoint
    esp_mountpoint="$(find_esp_mountpoint)" || {
        emit_event "error" "error" "No EFI system partition found."
        return 1
    }
    if [[ ! -f "${esp_mountpoint}/limine.conf" ]]; then
        emit_event "error" "error" "${esp_mountpoint}/limine.conf not found."
        return 1
    fi
    write_limine_conf "${esp_mountpoint}/limine.conf" "" || {
        emit_event "error" "error" "Failed to apply theme to ${esp_mountpoint}/limine.conf."
        return 1
    }
    emit_event "apply_theme_done" "info" "Theme applied to ${esp_mountpoint}/limine.conf."
}
